model: gd
# do_collect: False
name: gd
backbone: hratp64
camera_size: [1920, 1080]
visualize_cal: True
pose_estimator: eos
patch_type: 'face'
half: 1
ckpt_path: weights/concat_hratp_640_half.ckpt