model: ft
# do_collect: False
name: ft
backbone: hratp64
camera_size: [1920, 1080]
# visualize_cal: True
pose_estimator: eos
patch_type: 'face'
half: 1
ckpt_path: weights/hratp_640_half_vipl.ckpt
upsample_size: 640
patch_size: [160, 80, 40, 20]
atp_merge: transformer
# do_collect: 0
# do_finetune: 0
depth: 0
cam_idx: 0
id: 5
# batch_size: 6
# lr: 0.00001
# k: 9
# step: 100